version: "3.9"

services:
  php:
    build:
      context: ./.docker/php
    volumes:
      - ./:/app
    environment:
      - DB_TEST="postgresql://postgres:postgres@db:5432/spaceship?serverVersion=14&charset=utf8"

  web:
    image: nginx:latest
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - "80:80"

  db:
    image: bitnami/postgresql:14.1.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=spaceship
    volumes:
      - dbdata://bitnami/postgresql

volumes:
  dbdata: