version: "3.9"

services:

  php:
    build:
      context: ./.docker/php
      target: production
    volumes:
      - ./:/app

  web:
    image: nginx:1.21.6
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - "80:80"

  swagger-ui:
    image: swaggerapi/swagger-ui:v4.1.3
    ports:
      - '81:8080'
    volumes:
      - ./:/app
    environment:
      - SWAGGER_JSON=/app/.docker/openapi/swagger/swagger.json

  db:
    image: bitnami/postgresql:14.1.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=spaceship
    volumes:
      - db-data:/bitnami/postgresql

  prometheus:
    image: bitnami/prometheus:2.33.1
    ports:
      - "9090:9090"
    volumes:
      - ./.docker/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - prometheus-data:/opt/bitnami/prometheus/data

  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - "3000:3000"
    volumes:
      - ./.docker/grafana:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=spaceship
      - GF_SECURITY_ADMIN_PASSWORD=spaceship

  exporter:
    image: hipages/php-fpm_exporter:2.0.4
    ports:
      - "9253:9253"
    environment:
      PHP_FPM_SCRAPE_URI: "tcp://php:9000/status"

  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.1.0-community
    ports:
      - "9001:9000"
    volumes:
      - "sonar-data:/opt/sonarqube/data"
      - "sonar-logs:/opt/sonarqube/logs"
      - "sonar-extensions:/opt/sonarqube/extensions"
    networks:
      sonar-net:

  sonarqube-scanner-cli:
    container_name: sonarqube-scanner-cli
    image: sonarsource/sonar-scanner-cli:4.4
    working_dir: "/app"
    volumes:
      - "./:/app"
    depends_on:
      - sonarqube
    networks:
      sonar-net:

volumes:
  db-data:
  prometheus-data:
  grafana-data:
  sonar-data:
  sonar-logs:
  sonar-extensions:

networks:
  sonar-net: