version: "3.9"

services:
  php:
    build:
      context: ./.docker/php
    volumes:
      - ./:/app

  web:
    image: nginx:latest
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - "80:80"

  swagger-ui:
    image: swaggerapi/swagger-ui:v4.1.3
    ports:
      - '81:8080'
    volumes:
      - ./:/app
    environment:
      - SWAGGER_JSON=/app/.docker/openapi/swagger/swagger.json

  db:
    image: bitnami/postgresql:14.1.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=spaceship
    volumes:
      - dbdata://bitnami/postgresql

volumes:
  dbdata: